### ISSUE TITLE
[k8s-image-swapper]: chart clusterrole out of sync with 1.1.0 app version

### ISSUE THREAD

**Issue by KhrisRichardson-BO** [estahn/charts#48]
I believe 1.1.0 introduced the mutation of service accounts with image pull secrets, but the clusterrole in the chart doesn't yet reflect the new rules required.

Would it be possible to add a flag to toggle the service account mutation behavior?

Thanks

**Comment by estahn** [comment]
@KhrisRichardson-BO I see, that makes sense. I wonder if we should have a `serviceAccountReader` 🤔

**Comment by estahn** [comment]
https://github.com/estahn/charts/releases/tag/k8s-image-swapper-1.0.1
